"use server";

import { getCurrentUser } from "@/lib/auth";
import { can } from "@/lib/rbac";
import { rateLimit } from "@/lib/rate-limit";
import { fail, ok, type ActionResult } from "@/lib/actions/action-utils";
import { runAiTool } from "@/lib/ai/tool-handlers";
import { AI_TOOLS } from "@/lib/ai/tools";
import { callCloudflareAI } from "@/lib/ai/cloudflare";

export type ChatMessage = { role: "user" | "assistant"; content: string };
export interface AssistantAction { tool: string; url?: string; label: string; }
export interface AssistantReply {
  messages: ChatMessage[];
  actionsTaken: AssistantAction[];
  provider: string;
}

type ToolCall = { name: string; input: Record<string, unknown> };
type ModelEnvelope = { reply?: string; toolCalls?: ToolCall[] };

const MAX_TURNS = 30;
const MAX_MESSAGE_CHARS = 8000;
const RATE_LIMIT_PER_MINUTE = 20;

const TOOL_PERMISSION: Record<string, { module: "invoices" | "quotations" | "purchase_orders" | "billing" | "expenses" | "command_center" | "documents"; permission: "create" | "view" }> = {
  generate_invoice: { module: "invoices", permission: "create" },
  generate_quotation: { module: "quotations", permission: "create" },
  generate_purchase_order: { module: "purchase_orders", permission: "create" },
  generate_monthly_site_invoice: { module: "billing", permission: "create" },
  billing_status: { module: "billing", permission: "view" },
  record_expense: { module: "expenses", permission: "create" },
  expense_analysis: { module: "expenses", permission: "view" },
  create_task: { module: "command_center", permission: "create" },
  search_documents: { module: "documents", permission: "view" },
};

function aiAllowed(role: string) { return role === "ADMIN" || role === "OWNER"; }

function safeJson(text: string): ModelEnvelope | null {
  try { return JSON.parse(text) as ModelEnvelope; } catch {
    const start = text.indexOf("{");
    const end = text.lastIndexOf("}");
    if (start >= 0 && end > start) {
      try { return JSON.parse(text.slice(start, end + 1)) as ModelEnvelope; } catch { return null; }
    }
    return null;
  }
}

function systemPrompt(userName: string, tools: unknown) {
  return `You are Ratneswar AI, the internal executive operations assistant for Ratneswar Engineering. The signed-in user is ${userName}. They may speak Hindi, Hinglish or English. Understand natural Hindi/Hinglish and reply in concise Hinglish unless they request another language. Any email/document wording you draft should be polished professional English.

STRICT BUSINESS RULES:
1. Return ONLY valid JSON: {"reply":"helpful text","toolCalls":[{"name":"tool_name","input":{}}]}.
2. Use [] for toolCalls when you need missing information. Ask only the minimum questions actually missing.
3. NEVER invent or silently change amounts, rates, quantity, HSN/SAC, GST type/rate, bank details, vendor/client identity, invoice period, PO reference, or legal billing party.
4. Search existing masters with lookup_master when a name is supplied and saved details would help. If multiple matches are possible, ask which one.
5. PO, invoice and quotation numbers are generated by the ERP. Never make up a document number.
6. Financial document tools create DRAFT records for the user to review in the ERP. Say clearly that a draft was created.
7. For SSNNL/subcontract billing, use only the saved site billing profile. Never assume Ratneswar is the legal invoice supplier.
8. For expenses/payments, INTERNAL_TRANSFER is not an expense.
9. draft_email only drafts; it never sends mail.
10. If the user asks only for wording or explanation, do not call a write tool.
11. You may call multiple independent tools only when the user explicitly asks for multiple actions.

AVAILABLE ERP TOOLS:
${JSON.stringify(tools)}`;
}

function buildModelMessages(userName: string, history: ChatMessage[]) {
  const toolCatalog = AI_TOOLS.map((tool) => ({ name: tool.name, description: tool.description, input_schema: tool.input_schema }));
  return [
    { role: "system" as const, content: systemPrompt(userName, toolCatalog) },
    ...history.map((m) => ({ role: m.role, content: m.content })),
  ];
}

function prettyToolData(toolName: string, data: unknown): string | null {
  if (!data) return null;
  if (toolName === "draft_email") {
    const mail = data as { to?: string; subject?: string; body?: string };
    return `${mail.to ? `To: ${mail.to}\n` : ""}Subject: ${mail.subject || ""}\n\n${mail.body || ""}`.trim();
  }
  if (toolName === "lookup_master") {
    const d = data as { sites?: Array<{ name: string }>; clients?: Array<{ name: string }>; vendors?: Array<{ name: string }> };
    const lines = [
      ...(d.sites ?? []).map((x) => `Site: ${x.name}`),
      ...(d.clients ?? []).map((x) => `Client: ${x.name}`),
      ...(d.vendors ?? []).map((x) => `Vendor: ${x.name}`),
    ];
    return lines.length ? lines.join("\n") : "No matching master found.";
  }
  if (["billing_status", "expense_analysis"].includes(toolName)) return `\n${JSON.stringify(data, null, 2)}`;
  return null;
}

async function finalizeEnvelope(user: NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>, history: ChatMessage[], raw: string, model: string): Promise<AssistantReply> {
  const messages = history.slice();
  const actionsTaken: AssistantAction[] = [];
  const envelope = safeJson(raw);
  if (!envelope) {
    messages.push({ role: "assistant", content: raw.trim() || "Cloud AI response could not be parsed." });
    return { messages, actionsTaken, provider: `Cloudflare Workers AI · ${model}` };
  }

  const calls = Array.isArray(envelope.toolCalls) ? envelope.toolCalls.slice(0, 5) : [];
  if (!calls.length) {
    messages.push({ role: "assistant", content: envelope.reply?.trim() || "Done." });
    return { messages, actionsTaken, provider: `Cloudflare Workers AI · ${model}` };
  }

  const resultLines: string[] = [];
  for (const call of calls) {
    const permission = TOOL_PERMISSION[call.name];
    if (permission && !can(user.role, permission.module, permission.permission)) {
      resultLines.push(`${call.name}: Permission denied.`);
      continue;
    }
    try {
      const result = await runAiTool(call.name, call.input || {});
      resultLines.push(result.summary);
      const formatted = prettyToolData(call.name, result.data);
      if (formatted) resultLines.push(formatted);
      const data = result.data as { url?: string; invoiceNo?: string; quoteNo?: string; poNo?: string; id?: string } | null;
      if (data?.url) actionsTaken.push({ tool: call.name, url: data.url, label: data.invoiceNo ?? data.quoteNo ?? data.poNo ?? (call.name === "create_task" ? "Open Dashboard" : call.name === "record_expense" ? "Open Expenses" : "Open Record") });
      if (call.name === "search_documents" && Array.isArray(result.data)) {
        for (const doc of (result.data as Array<{ name?: string; url?: string }>).slice(0, 5)) if (doc.url) actionsTaken.push({ tool: call.name, url: doc.url, label: doc.name || "Open Document" });
      }
    } catch (error) {
      resultLines.push(`${call.name}: ${error instanceof Error ? error.message : "Tool execution failed."}`);
    }
  }

  const intro = envelope.reply?.trim();
  messages.push({ role: "assistant", content: [intro, ...resultLines].filter(Boolean).join("\n\n") || "Done." });
  return { messages, actionsTaken, provider: `Cloudflare Workers AI · ${model}` };
}

function validateHistory(history: ChatMessage[]) {
  if (!Array.isArray(history) || history.length === 0) return "No message provided.";
  if (history.length > MAX_TURNS) return "This conversation is too long. Start a new chat.";
  if (history.some((m) => !m || !["user", "assistant"].includes(m.role) || typeof m.content !== "string" || m.content.length > MAX_MESSAGE_CHARS)) return "A message is invalid or too long.";
  return null;
}

export async function sendAssistantMessage(history: ChatMessage[]): Promise<ActionResult<AssistantReply>> {
  const user = await getCurrentUser();
  if (!user) return fail("Not signed in.");
  if (!aiAllowed(user.role)) return fail("Ratneswar AI is available only to Owner and Admin.");
  const invalid = validateHistory(history);
  if (invalid) return fail(invalid);
  const limited = rateLimit(`ai-assistant:${user.id}`, RATE_LIMIT_PER_MINUTE, 60_000);
  if (!limited.ok) return fail(`Too many requests. Try again in ${Math.ceil(limited.retryAfterMs / 1000)} seconds.`);

  const model = process.env.CLOUDFLARE_AI_MODEL || "@cf/zai-org/glm-4.7-flash";
  try {
    const raw = await callCloudflareAI(buildModelMessages(user.name, history), model);
    return ok(await finalizeEnvelope(user, history, raw, model));
  } catch (error) {
    return fail(`${error instanceof Error ? error.message : "Cloud AI is unavailable."} The ERP itself remains available.`);
  }
}
