"use client";
import * as React from "react";
import { Building2, MoreHorizontal, Pencil, Plus, ShoppingCart, Trash2 } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAction } from "@/hooks/use-action";
import { createVendorMaster, deleteVendorMaster, updateVendorMaster } from "@/lib/actions/vendor-actions";
import type { VendorMasterItem } from "@/lib/queries/vendors";
import { formatDate, formatINR } from "@/lib/utils";

const empty={code:"",name:"",contactPerson:"",phone:"",email:"",address:"",gstin:"",pan:""};
function VendorDialog({vendor}:{vendor?:VendorMasterItem}){const [open,setOpen]=React.useState(false);const [form,setForm]=React.useState(vendor?{code:vendor.code??"",name:vendor.name,contactPerson:vendor.contactPerson??"",phone:vendor.phone??"",email:vendor.email??"",address:vendor.address??"",gstin:vendor.gstin??"",pan:vendor.pan??""}:empty);const action=vendor?updateVendorMaster.bind(null,vendor.id):createVendorMaster;const {run,loading}=useAction(action,{successMessage:"Vendor saved",onSuccess:()=>setOpen(false)});const set=(k:keyof typeof form,v:string)=>setForm(f=>({...f,[k]:v}));return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>{vendor?<DropdownMenuItem onSelect={(e)=>{e.preventDefault();setOpen(true)}}><Pencil className="mr-2 h-4 w-4"/>Edit vendor</DropdownMenuItem>:<Button><Plus className="h-4 w-4"/>Add Vendor</Button>}</DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{vendor?"Edit":"Add"} Vendor</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-1.5"><Label>Vendor Code</Label><Input value={form.code} onChange={e=>set("code",e.target.value.toUpperCase())}/></div><div className="space-y-1.5"><Label>Vendor Name</Label><Input value={form.name} onChange={e=>set("name",e.target.value)}/></div><div className="space-y-1.5"><Label>GSTIN</Label><Input value={form.gstin} onChange={e=>set("gstin",e.target.value.toUpperCase())}/></div><div className="space-y-1.5"><Label>PAN</Label><Input value={form.pan} onChange={e=>set("pan",e.target.value.toUpperCase())}/></div><div className="space-y-1.5"><Label>Contact Person</Label><Input value={form.contactPerson} onChange={e=>set("contactPerson",e.target.value)}/></div><div className="space-y-1.5"><Label>Phone</Label><Input value={form.phone} onChange={e=>set("phone",e.target.value)}/></div><div className="space-y-1.5 sm:col-span-2"><Label>Email</Label><Input type="email" value={form.email} onChange={e=>set("email",e.target.value)}/></div><div className="space-y-1.5 sm:col-span-2"><Label>Address</Label><Textarea rows={3} value={form.address} onChange={e=>set("address",e.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button loading={loading} disabled={!form.name.trim()} onClick={()=>run(form)}>Save Vendor</Button></DialogFooter></DialogContent></Dialog>}
export function VendorMasterClient({vendors}:{vendors:VendorMasterItem[]}){const {run:remove}=useAction(deleteVendorMaster,{successMessage:"Vendor deleted"});return <div className="space-y-5"><div className="flex justify-end"><VendorDialog/></div>{vendors.length===0?<Card className="p-12 text-center text-sm text-slate-500">No vendors yet.</Card>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{vendors.map(v=><Card key={v.id} className="p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><div className="rounded-xl bg-emerald-50 p-2.5 text-emerald-700"><Building2 className="h-5 w-5"/></div><div className="min-w-0"><h3 className="truncate font-semibold">{v.name}</h3><p className="text-xs text-slate-500">{v.code||v.gstin||"Vendor master"}</p></div></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon"><MoreHorizontal className="h-4 w-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><VendorDialog vendor={v}/><DropdownMenuItem className="text-rose-600" onClick={()=>remove(v.id)}><Trash2 className="mr-2 h-4 w-4"/>Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div><div className="mt-4 space-y-1.5 text-sm"><p><span className="text-slate-500">Contact:</span> {v.contactPerson||v.phone||"—"}</p><p><span className="text-slate-500">Email:</span> {v.email||"—"}</p><p className="line-clamp-2 text-slate-500">{v.address||"No address"}</p></div><div className="mt-4 border-t pt-3 text-xs text-slate-500"><div className="flex items-center justify-between"><span className="flex items-center gap-1"><ShoppingCart className="h-3.5 w-3.5"/>{v._count.purchaseOrders} POs</span>{v.purchaseOrders[0]&&<span>Last: {formatDate(v.purchaseOrders[0].date)} · {formatINR(v.purchaseOrders[0].grandTotal)}</span>}</div></div></Card>)}</div>}</div>}
